### ISSUE TITLE
请问下怎么跳转其他页面呢

### ISSUE THREAD

**Issue by Caraws** [itorr/q.js#8]
新手提问.... 比如现在在HOME页面,在回调里面怎么去跳转其他的页面呢..

**Comment by itorr** [comment]
普通的 HTML 链接形式 `<a href="#/about">关于</a>` 、或者 通过 JavaScript 修改 hash 都可以进行跳转

**Comment by Caraws** [comment]
噢噢...  谢谢

**Comment by zhengju1893** [comment]
请教一下，我弄了半天也不清楚怎样实现页面之间的路由。能不能给个demo啊。我的需求是，从a页面拿到b页面渲染到a页面指定的容器中。谢谢了。

**Comment by zhengju1893** [comment]
给个实例代码也行啊亲。。

**Comment by blqw** [comment]
这个路由是用来触发回调事件的  如果要加载页面, 请在回调中设置页面加载的逻辑代码
